// Package setup provides dependency detection, portable tool installation,
// and shell environment activation for the BitCLI self-contained setup flow.
package setup

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

// EnvWriter generates shell activation files that prepend BitCLI's bundled
// tool directories to PATH so cmake, clang, and uv are found without system
// installation.
type EnvWriter struct {
	BitcliHome string
}

// NewEnvWriter returns an EnvWriter for the given BitCLI home directory.
func NewEnvWriter(bitcliHome string) *EnvWriter {
	return &EnvWriter{BitcliHome: bitcliHome}
}

// toolDirs returns the bin directories for all bundled tools.
func (e *EnvWriter) toolDirs() []string {
	return []string{
		filepath.Join(e.BitcliHome, "bin"),
		filepath.Join(e.BitcliHome, "tools", "ninja"),
		filepath.Join(e.BitcliHome, "tools", "cmake"),
		filepath.Join(e.BitcliHome, "tools", "cmake", "bin"),
		filepath.Join(e.BitcliHome, "tools", "clang"),
		filepath.Join(e.BitcliHome, "tools", "clang", "bin"),
		filepath.Join(e.BitcliHome, "tools", "llvm", "bin"),
		filepath.Join(e.BitcliHome, "tools", "uv"),
	}
}

// Write writes env.ps1 (Windows) and env.sh (POSIX) into BitcliHome.
func (e *EnvWriter) Write() error {
	if err := e.writePS1(); err != nil {
		return err
	}
	return e.writeSH()
}

// writePS1 writes the PowerShell activation script.
func (e *EnvWriter) writePS1() error {
	dirs := e.toolDirs()
	var sb strings.Builder
	sb.WriteString("# BitCLI environment — generated by `bitcli setup`\n")
	sb.WriteString("# Source this file to activate BitCLI tools in the current shell:\n")
	sb.WriteString("#   . $HOME\\.bitcli\\env.ps1\n")
	sb.WriteString("# To activate permanently, add the above line to your $PROFILE.\n\n")

	sb.WriteString("$_bitcliPaths = @(\n")
	for _, d := range dirs {
		sb.WriteString(fmt.Sprintf("    %q\n", d))
	}
	sb.WriteString(")\n\n")
	sb.WriteString("foreach ($p in $_bitcliPaths) {\n")
	sb.WriteString("    if (Test-Path $p) {\n")
	sb.WriteString("        $env:PATH = \"$p;$env:PATH\"\n")
	sb.WriteString("    }\n")
	sb.WriteString("}\n")
	sb.WriteString("Remove-Variable _bitcliPaths\n")

	return writeFile(filepath.Join(e.BitcliHome, "env.ps1"), sb.String())
}

// writeSH writes the POSIX sh activation script.
func (e *EnvWriter) writeSH() error {
	dirs := e.toolDirs()
	var sb strings.Builder
	sb.WriteString("# BitCLI environment — generated by `bitcli setup`\n")
	sb.WriteString("# Source this file to activate BitCLI tools in the current shell:\n")
	sb.WriteString("#   . \"$HOME/.bitcli/env.sh\"\n")
	sb.WriteString("# To activate permanently, add the above line to ~/.bashrc or ~/.zshrc.\n\n")

	for _, d := range dirs {
		sb.WriteString(fmt.Sprintf("[ -d %q ] && export PATH=%q:\"$PATH\"\n", d, d))
	}

	return writeFile(filepath.Join(e.BitcliHome, "env.sh"), sb.String())
}

// InjectPATH prepends all bundled tool bin dirs that exist into the current
// process's PATH environment variable. Called at binary startup so installed
// tools are always discoverable without manual shell sourcing.
func InjectPATH(bitcliHome string) {
	dirs := []string{
		filepath.Join(bitcliHome, "bin"),
		filepath.Join(bitcliHome, "tools", "ninja"),
		filepath.Join(bitcliHome, "tools", "cmake"),
		filepath.Join(bitcliHome, "tools", "cmake", "bin"),
		filepath.Join(bitcliHome, "tools", "clang"),
		filepath.Join(bitcliHome, "tools", "clang", "bin"),
		filepath.Join(bitcliHome, "tools", "llvm", "bin"),
		filepath.Join(bitcliHome, "tools", "uv"),
	}

	sep := ":"
	if runtime.GOOS == "windows" {
		sep = ";"
	}

	current := os.Getenv("PATH")
	var prepend []string
	for _, d := range dirs {
		if _, err := os.Stat(d); err == nil {
			prepend = append(prepend, d)
		}
	}
	if len(prepend) > 0 {
		_ = os.Setenv("PATH", strings.Join(prepend, sep)+sep+current)
	}
}

// PrintActivationHint prints a user-friendly hint about sourcing the env file.
func PrintActivationHint(out io.Writer, bitcliHome string) {
	if runtime.GOOS == "windows" {
		fmt.Fprintf(out, "\nTo activate BitCLI tools in future shells, add this to your PowerShell profile:\n")
		fmt.Fprintf(out, "  . %q\n\n", filepath.Join(bitcliHome, "env.ps1"))
		fmt.Fprintf(out, "To find your profile path, run:  echo $PROFILE\n\n")
	} else {
		fmt.Fprintf(out, "\nTo activate BitCLI tools in future shells, add this to ~/.bashrc or ~/.zshrc:\n")
		fmt.Fprintf(out, "  . \"%s\"\n\n", filepath.Join(bitcliHome, "env.sh"))
	}
}

func writeFile(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}
